import {afterEach,expect,it,vi} from 'vitest';
import {Chat,trustedReconnect} from '../electron/chat';
import {youtubeBatches} from '../electron/youtube-stream';
vi.mock('../electron/youtube-stream',()=>({youtubeBatches:vi.fn()}));
const chats:Chat[]=[];afterEach(()=>{chats.splice(0).forEach(c=>c.stop());vi.useRealTimers();vi.unstubAllGlobals();vi.clearAllMocks();});
const credentials=async()=>({account:{id:'owner'},access_token:'fixture-token',clientId:'fixture-client',scope:['user:read:chat','user:write:chat']});
class Socket{static list:Socket[]=[];readyState=1;onmessage:any;onclose:any;onerror:any;constructor(readonly url:string){Socket.list.push(this);}close(){this.readyState=3;this.onclose?.();}send(data:any){this.onmessage?.({data:JSON.stringify(data)});}}
const settle=()=>new Promise(r=>setTimeout(r,0));
it('refuses a reconnect URL that would expose the Twitch connection to another host',()=>{expect(trustedReconnect('wss://eventsub.wss.twitch.tv/ws?session=test')).toBe(true);for(const url of ['wss://evil.test/ws','wss://eventsub.wss.twitch.tv.evil.test','ws://eventsub.wss.twitch.tv/ws','wss://user:secret@eventsub.wss.twitch.tv/ws'])expect(trustedReconnect(url)).toBe(false);});
it('leaves existing streaming credentials usable but explicitly requests added chat scopes',async()=>{const c=new Chat({credentials:async()=>({...await credentials(),scope:['channel:read:stream_key']})} as any,()=>{});chats.push(c);await c.start(['twitch']);await settle();expect(c.status.twitch.state).toBe('reauthorize');});
it('deduplicates Twitch notifications, excludes self replies and removes moderated messages',async()=>{Socket.list=[];vi.stubGlobal('WebSocket',Socket);vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({data:[{is_sent:true}]}))));const received=vi.fn(),c=new Chat({credentials} as any,received);chats.push(c);await c.start(['twitch']);await settle();const ws=Socket.list[0];ws.send({metadata:{message_type:'session_welcome'},payload:{session:{id:'fixture'}}});await settle();expect(c.status.twitch.state).toBe('connected');const note=(id:string,user:string,type='channel.chat.message')=>({metadata:{message_type:'notification',message_timestamp:new Date().toISOString()},payload:{subscription:{type},event:{message_id:id,chatter_user_id:user,chatter_user_name:'Viewer',message:{text:'Hello'}}}});ws.send(note('one','viewer'));ws.send(note('one','viewer'));ws.send(note('two','owner'));await settle();expect(received).toHaveBeenCalledTimes(1);expect(c.messages).toHaveLength(2);await c.send(c.messages[0],'Reply');expect(c.status.twitch.sent).toBe(1);ws.send(note('one','viewer','channel.chat.message_delete'));await settle();expect(c.messages.map(m=>m.id)).toEqual(['two']);c.stop();expect(c.status.twitch.state).toBe('off');expect(ws.readyState).toBe(3);});
it('receives a YouTube stream with historical suppression and no polling requests',async()=>{const received=vi.fn(),now=new Date().toISOString();const item=(id:string,author='viewer',type=1)=>({id,snippet:{type,publishedAt:now,displayMessage:'hello'},authorDetails:{channelId:author,displayName:'Viewer'}});vi.mocked(youtubeBatches).mockImplementation(async function*(){yield {nextPageToken:'page-1',items:[item('history')]};yield {nextPageToken:'page-2',items:[item('new'),item('own','owner'),item('new')]};yield {nextPageToken:'page-3',items:[item('new','viewer',2)]};});const fetcher=vi.fn(async()=>new Response(JSON.stringify({items:[{snippet:{liveChatId:'fixture-chat'}}]})));vi.stubGlobal('fetch',fetcher);const c=new Chat({credentials} as any,received);chats.push(c);await c.start(['youtube']);await settle();await settle();expect(received).toHaveBeenCalledTimes(1);expect(c.messages.map(m=>m.id)).toEqual(['history','own']);expect(fetcher).toHaveBeenCalledTimes(1);expect(String(fetcher.mock.calls[0][0])).toContain('liveBroadcasts?');});
