import {afterEach,describe,it,expect,vi} from 'vitest';import {neuralSpeech} from '../electron/neural-speech';
afterEach(()=>vi.unstubAllGlobals());
const wave=()=>{const b=Buffer.alloc(44+48000);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(24000,24);b.writeUInt32LE(48000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(48000,40);b.writeInt16LE(1000,48);return b;};
describe('local neural voice boundary',()=>{
 it('routes Melo to its own loopback service without sending a Qwen speaker',async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(wave(),{headers:{'Content-Type':'audio/wav'}}));vi.stubGlobal('fetch',fetcher);await neuralSpeech('hello','ryan','en',new AbortController().signal,'melo');expect(fetcher.mock.calls[0][0]).toBe('http://127.0.0.1:11437/speech');expect(JSON.parse(fetcher.mock.calls[0][1].body).voice).toBe('');});
 it('rejects fully silent generated speech',async()=>{const data=wave();data.fill(0,44);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(data,{headers:{'Content-Type':'audio/wav'}})));await expect(neuralSpeech('hello','','en',new AbortController().signal)).rejects.toThrow('host.neuralUnavailable');});
 it('uses only the fixed loopback service and rejects redirects',async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(wave(),{headers:{'Content-Type':'audio/wav'}}));vi.stubGlobal('fetch',fetcher);const result=await neuralSpeech('Hello','','en',new AbortController().signal);expect(result.duration).toBe(1);expect(fetcher.mock.calls[0][0]).toBe('http://127.0.0.1:11435/speech');expect(fetcher.mock.calls[0][1].redirect).toBe('error');});
 it('does not play an HTML error page or malformed WAV',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('<html>error</html>',{headers:{'Content-Type':'text/html'}})));await expect(neuralSpeech('Hi','','en',new AbortController().signal)).rejects.toThrow('host.neuralUnavailable');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('invalid',{headers:{'Content-Type':'audio/wav'}})));await expect(neuralSpeech('Hi','','en',new AbortController().signal)).rejects.toThrow();});
 it('does not send text from a cancelled session',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const controller=new AbortController();controller.abort();await expect(neuralSpeech('old text','','en',controller.signal)).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled();});
});
