import { readFile, writeFile, mkdir, stat, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { Store, atomicWrite } from './storage';
import { OAuth } from './oauth';
import { Chat } from './chat';
import { Speech } from './speech';
import {neuralHealth,neuralSpeech} from './neural-speech';
import {HostDirector} from './host-director';
import {replyLanguage} from '../shared/reply-language';
import { generateHostText, warmHostModel } from './host-model';
import { hostConfigSchema, blankOverlay, type HostConfig, type HostSnapshot, type ChatMessage, type Utterance, type OverlayState } from '../shared/hosting';
import { providers, type Provider } from '../shared/types';
export class Hosting {
 config=hostConfigSchema.parse({});running=false;warming=false;error='';utterance:Utterance|null=null;
 readonly chat:Chat;readonly speech:Speech;voices:HostSnapshot['voices']=[];
 readonly stats={startedAt:0,generated:0,spoken:0,replies:0,failures:0};readonly overlay=Object.fromEntries(providers.map(p=>[p,blankOverlay()])) as HostSnapshot['overlay'];
 private controller?:AbortController;private timer?:ReturnType<typeof setInterval>;private pending:ChatMessage[]=[];private history:string[]=[];private hourly:number[]=[];private lastComment=0;private lastReply=0;private busy=false;
 private director=new HostDirector();private requestTimes:number[]=[];
 readonly timing={modelMs:0,speechMs:0,responseP95Ms:0};
 readonly assets:string;private audio=new Map<string,Buffer>();
 constructor(private store:Store,auth:OAuth,private context:()=>string,private youtubeId:()=>string|undefined,private gameConnected:()=>boolean|undefined=()=>undefined,chatMode:'live'|'simulation'='live'){this.assets=join(store.directory,'host-assets');this.speech=new Speech(join(store.directory,'host-audio'));this.chat=new Chat(auth,m=>{if(this.running&&Date.now()-m.at<60000&&!this.blocked(m.text)){this.pending.push(m);if(this.pending.length>12)this.pending.shift();}},chatMode);}
 private blocked(text:string){const value=text.toLocaleLowerCase();return this.config.blockedWords.some(word=>value.includes(word.toLocaleLowerCase()));}
 async init(){await mkdir(this.assets,{recursive:true});try{this.config=hostConfigSchema.parse(JSON.parse(await readFile(join(this.store.directory,'host.json'),'utf8')));}catch(e:any){if(e.code!=='ENOENT')this.error='host.configError';}this.voices=await this.speech.voices().catch(()=>[]);}
 async save(value:unknown){const next=hostConfigSchema.safeParse(value);if(!next.success)throw new Error('host.configError');if(this.running)throw new Error('host.stopFirst');await atomicWrite(join(this.store.directory,'host.json'),JSON.stringify(next.data));this.config=next.data;}
 async saveLayouts(value:unknown){const next=hostConfigSchema.shape.layouts.safeParse(value);if(!next.success)throw new Error('host.configError');const config={...this.config,layouts:next.data};await atomicWrite(join(this.store.directory,'host.json'),JSON.stringify(config));this.config=config;}
 async key(value:string){if(this.running)throw new Error('host.stopFirst');if(typeof value!=='string'||value.length>4096||/[\r\n]/.test(value))throw new Error('host.configError');await this.store.set('host.modelKey',value.trim()||undefined);}
 async importAsset(path:string){if((await stat(path)).size>60_000_000)throw new Error('host.assetInvalid');const data=await readFile(path);if(data.length>60_000_000)throw new Error('host.assetInvalid');let ext='';if(data.subarray(1,4).toString()==='PNG')ext='png';else if(data[0]===255&&data[1]===216)ext='jpg';else if(data.subarray(0,4).toString()==='RIFF'&&data.subarray(8,12).toString()==='WEBP')ext='webp';else if(data.subarray(0,4).toString()==='glTF'){
  try{const length=data.readUInt32LE(12);const gltf=JSON.parse(data.subarray(20,20+length).toString());if(!gltf.extensions?.VRM&&!gltf.extensions?.VRMC_vrm)throw 0;if([...(gltf.buffers??[]),...(gltf.images??[])].some((b:any)=>b.uri&&!b.uri.startsWith('data:')))throw 0;ext='vrm';}catch{throw new Error('host.assetInvalid');}
 }if(!ext)throw new Error('host.assetInvalid');const asset=randomBytes(16).toString('hex')+'.'+ext;await writeFile(join(this.assets,asset),data);try{await this.save({...this.config,avatar:{...this.config.avatar,kind:ext==='vrm'?'vrm':'image',asset}});}catch(e){await unlink(join(this.assets,asset));throw e;}return asset;}
 async snapshot():Promise<HostSnapshot>{return {config:this.config,running:this.running,warming:this.warming,hasKey:!!await this.store.get('host.modelKey'),utterance:this.utterance,messages:this.chat.messages,chat:this.chat.status,error:this.error,voices:this.voices,stats:this.stats,overlay:this.overlay,timing:this.timing};}
 forOutput(provider:Provider):OverlayState{return {gameConnected:this.gameConnected(),layout:this.config.layouts[provider],avatar:this.config.avatar,language:this.config.language,provider,messages:this.chat.messages.filter(m=>m.platform===provider&&!this.blocked(m.text)).slice(-12),utterance:this.utterance&&(this.utterance.scope==='all'||this.utterance.scope===provider)&&this.utterance.expires>Date.now()?this.utterance:null};}
 audioData(id:string){return this.audio.get(id);}
 async start(){if(this.running)return;if(!this.config.apiBase||!this.config.model)throw new Error('host.modelRequired');this.error='';const controller=new AbortController();this.controller=controller;this.running=true;this.warming=true;this.pending=[];this.history=[];this.hourly=[];this.director.reset();this.requestTimes=[];Object.assign(this.stats,{startedAt:Date.now(),generated:0,spoken:0,replies:0,failures:0});this.lastComment=0;this.lastReply=0;try{if(this.config.speech&&this.config.speechProvider!=='system'&&!await neuralHealth(this.config.speechProvider))throw new Error('host.neuralUnavailable');await warmHostModel(this.config,controller.signal);if(controller.signal.aborted)return;this.warming=false;await this.chat.start(this.config.chatPlatforms,this.youtubeId());this.timer=setInterval(()=>void this.tick(),1000);}catch(e){if(!controller.signal.aborted){this.stop();this.error=e instanceof Error&&e.message==='host.neuralUnavailable'?e.message:'host.modelFailed';throw e;}}}
 stop(){this.running=false;this.warming=false;this.controller?.abort();if(this.timer)clearInterval(this.timer);this.chat.stop();this.pending=[];this.utterance=null;this.audio.clear();}
 async testVoice(){if(this.running)throw new Error('host.stopFirst');const texts={'zh-CN':'你好，我是你的虚拟游戏主播。现在开始语音测试。','zh-TW':'你好，我是你的虛擬遊戲主播。現在開始語音測試。',ja:'こんにちは。ゲーム配信の音声テストです。',ko:'안녕하세요. 게임 방송 음성 테스트입니다.',en:'Hello. This is your virtual game host speaking.'};this.controller?.abort();const controller=new AbortController();this.controller=controller;this.error='';await this.publish(texts[this.config.language],'all',controller.signal);}
 private async publish(text:string,scope:Provider|'all',signal:AbortSignal,stillRelevant=()=>true,language:HostConfig['language']=this.config.language,replyTo?:string){let audio:string|undefined,duration=8;if(this.config.speech){try{const started=Date.now();const result=this.config.speechProvider!=='system'?await neuralSpeech(text,language===this.config.language?this.config.neuralVoice:'',language,signal,this.config.speechProvider):await this.speech.synthesize(text,language===this.config.language?this.config.voice:'',language,signal);this.timing.speechMs=Date.now()-started;if(signal.aborted||!stillRelevant())return;audio=result.id;duration=Math.min(40,result.duration);this.audio.set(audio,result.data);while(this.audio.size>3)this.audio.delete(this.audio.keys().next().value!);this.stats.spoken++;}catch{if(signal.aborted)return;this.error=this.config.speechProvider!=='system'?'host.neuralUnavailable':'host.speechError';this.stats.failures++;}}if(signal.aborted||!stillRelevant())return;this.utterance={id:randomBytes(12).toString('hex'),text,scope,audio,language,replyTo,at:Date.now(),expires:Date.now()+Math.max(10000,(duration+4)*1000)};}
 private async tick(){if(!this.running||this.busy||!this.controller)return;const now=Date.now(),context=this.context();this.director.observe(context,now);if(this.utterance&&now<this.utterance.expires)return;this.hourly=this.hourly.filter(t=>now-t<3600000);if(this.hourly.length>=this.config.maxPerHour)return;
  this.pending=this.pending.filter(m=>now-m.at<60000&&this.chat.messages.some(v=>v.platform===m.platform&&v.id===m.id));const picked=now-this.lastReply>=this.config.replyCooldownSec*1000?this.director.choose(this.pending,now):undefined,chat=picked?.message,direction=this.director.direction(this.config,now,this.lastComment);
  if(!chat&&(!this.config.commentary||!direction))return;this.busy=true;let errorKey='host.modelFailed';const signal=this.controller.signal;this.hourly.push(now);if(chat)this.lastReply=now;else {this.lastComment=now;this.director.commented();}
  try{this.error='';const stillRelevant=()=>!chat||Date.now()-chat.at<60000&&this.chat.messages.some(m=>m.platform===chat.platform&&m.id===chat.id);const language=chat?replyLanguage(chat.text):this.config.language;const text=await generateHostText({...this.config,language},await this.store.get<string>('host.modelKey')??'',context,chat,this.history.filter(text=>replyLanguage(text)===language),signal,{...(chat?{reason:'viewer'}:direction),previousConversation:picked?.previous,similarQuestions:picked?.similar});this.timing.modelMs=Date.now()-now;if(signal.aborted||!stillRelevant())return;this.stats.generated++;if(this.blocked(text)||!chat&&this.history.includes(text))return;this.history.push(text);this.history=this.history.slice(-8);errorKey='host.speechError';await this.publish(text,chat?.platform??'all',signal,stillRelevant,language,chat?.id);if(signal.aborted||!stillRelevant())return;this.requestTimes.push(Date.now()-now);this.requestTimes=this.requestTimes.slice(-100);const sorted=[...this.requestTimes].sort((a,b)=>a-b);this.timing.responseP95Ms=sorted[Math.ceil(sorted.length*.95)-1]??0;if(chat)this.director.answered(chat,text,Date.now());if(chat&&this.config.textReplies&&!signal.aborted&&this.chat.messages.some(m=>m.id===chat.id&&m.platform===chat.platform)){errorKey='host.chatSendFailed';await this.chat.send(chat,text);this.stats.replies++;}}
  catch(e){if(!signal.aborted){this.error=e instanceof Error&&e.message.startsWith('host.')?e.message:errorKey;this.stats.failures++;}}
  finally{this.busy=false;}
 }
}
