import { spawn } from 'node:child_process';
import { readFile, mkdir, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
// Text and voice are JSON on stdin, never interpolated into shell code or command arguments.
const script=`$ErrorActionPreference='Stop'; [Console]::InputEncoding=[Text.Encoding]::UTF8; [Console]::OutputEncoding=[Text.Encoding]::UTF8; Add-Type -AssemblyName System.Speech; $v=[Console]::In.ReadToEnd()|ConvertFrom-Json; $s=New-Object System.Speech.Synthesis.SpeechSynthesizer; try { if($v.op -eq 'voices'){ @($s.GetInstalledVoices()|ForEach-Object { @{name=$_.VoiceInfo.Name;language=$_.VoiceInfo.Culture.Name} })|ConvertTo-Json -Compress } else { if($v.voice){$s.SelectVoice($v.voice)} else { $lang=$v.language.Split('-')[0]; $matching=@($s.GetInstalledVoices()|Where-Object {$_.Enabled -and $_.VoiceInfo.Culture.TwoLetterISOLanguageName -eq $lang}); if($matching.Count -eq 0){throw 'Voice language unavailable'}; $exact=@($matching|Where-Object {$_.VoiceInfo.Culture.Name -eq $v.language}); if($exact.Count -gt 0){$s.SelectVoice($exact[0].VoiceInfo.Name)}else{$s.SelectVoice($matching[0].VoiceInfo.Name)} }; $s.SetOutputToWaveFile($v.output);$s.Speak($v.text) } } finally {$s.Dispose()}`;
function run(value:unknown,signal?:AbortSignal):Promise<string>{return new Promise((resolve,reject)=>{const child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-EncodedCommand',Buffer.from(script,'utf16le').toString('base64')],{windowsHide:true,stdio:'pipe'});let output='';const timer=setTimeout(()=>child.kill(),45000);const abort=()=>child.kill();signal?.addEventListener('abort',abort,{once:true});child.stdout.on('data',b=>{output+=b.toString('utf8');if(output.length>20000)child.kill();});child.stderr.resume();child.stdin.on('error',()=>{});child.on('error',()=>reject(new Error('speech.unavailable')));child.on('close',code=>{clearTimeout(timer);signal?.removeEventListener('abort',abort);code===0&&!signal?.aborted?resolve(output.trim()):reject(new Error('speech.unavailable'));});child.stdin.end(JSON.stringify(value));});}
export class Speech {
 constructor(private directory:string){}
 async voices(){const value=JSON.parse(await run({op:'voices'}));return (Array.isArray(value)?value:[value]) as {name:string;language:string}[];}
 async synthesize(text:string,voice:string,language:string,signal:AbortSignal){await mkdir(this.directory,{recursive:true});const id=randomBytes(16).toString('hex')+'.wav',output=join(this.directory,id);try{await run({op:'speak',text:text.slice(0,600),voice,language,output},signal);const data=await readFile(output);if(data.length<44||data.length>20_000_000||waveIsSilent(data))throw new Error('speech.unavailable');return {id,data,duration:waveDuration(data)};}finally{await unlink(output).catch(()=>{});}}
}
export function waveDuration(data:Buffer){if(data.toString('ascii',0,4)!=='RIFF'||data.toString('ascii',8,12)!=='WAVE')throw new Error('speech.unavailable');let rate=0,size=0;for(let at=12;at+8<=data.length;){const length=data.readUInt32LE(at+4),id=data.toString('ascii',at,at+4);if(at+8+length>data.length)throw new Error('speech.unavailable');if(id==='fmt '&&length>=16)rate=data.readUInt32LE(at+16);if(id==='data')size=length;at+=8+length+(length%2);}if(!rate||!size)throw new Error('speech.unavailable');return size/rate;}
export function waveIsSilent(data:Buffer){let pcm16=false;for(let at=12;at+8<=data.length;){const length=data.readUInt32LE(at+4),id=data.toString('ascii',at,at+4);if(at+8+length>data.length)return false;if(id==='fmt '&&length>=16)pcm16=data.readUInt16LE(at+8)===1&&data.readUInt16LE(at+22)===16;if(id==='data'&&pcm16){for(let i=at+8;i+1<at+8+length;i+=2)if(Math.abs(data.readInt16LE(i))>8)return false;return true;}at+=8+length+(length%2);}return false;}
