// Isolated desktop UI and local speech acceptance. No platform credentials or posts.
const {_electron:electron}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),data=await fs.mkdtemp(path.join(process.env.LOCALAPPDATA,'JEV Studio HostingTest-')),out=path.join(root,'test-results');await fs.mkdir(out,{recursive:true});const env={...process.env,JEV_TEST_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;delete env.JEV_DEV_URL;let app;const errors=[];
try{app=await electron.launch({args:[root],env,timeout:60000});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.studio-grid');await page.locator('.nav-item').nth(1).click();await page.waitForSelector('.layout-stage');
 const before=await page.evaluate(()=>window.studio.hostSnapshot());const target=page.locator('[data-layer=avatar]'),box=await target.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+40,box.y+box.height/2-30,{steps:5});await page.mouse.up();await page.locator('.layout-inspector .primary-button').click();await page.waitForFunction(x=>window.studio.hostSnapshot().then(s=>s.config.layouts.twitch.avatar.x!==x),before.config.layouts.twitch.avatar.x);const saved=await page.evaluate(()=>window.studio.hostSnapshot());assert(saved.config.layouts.twitch.avatar.x>before.config.layouts.twitch.avatar.x);assert.deepEqual(saved.config.layouts.youtube,before.config.layouts.youtube);
 const languages=['zh-CN','zh-TW','ja','ko','en'];for(const language of languages){await page.selectOption('#language',language);await page.waitForFunction(l=>document.documentElement.lang===l,language);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1080,820));assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Layout overflow: '+language);assert(!/host\.[a-zA-Z]/.test(await page.locator('.host-panel').innerText()));}
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1480,960));await page.selectOption('#language','zh-CN');await page.screenshot({path:path.join(out,'hosting-layout.png'),fullPage:true});
 const speech=await page.evaluate(async()=>{const h=await window.studio.hostSnapshot();const voice=h.voices.find(v=>v.language==='zh-CN')??h.voices[0];if(!voice)throw new Error('No installed local voice');await window.studio.saveHostConfig({...h.config,voice:voice.name,language:voice.language==='zh-CN'?'zh-CN':'en'});const url=await window.studio.testHostVoice();const a=new Audio(url);await a.play();a.pause();return {voices:h.voices,testVoice:voice.name,utterance:(await window.studio.hostSnapshot()).utterance};});assert(speech.utterance.audio);assert(speech.utterance.expires>speech.utterance.at);
 await page.evaluate(async()=>{const h=await window.studio.hostSnapshot();await window.studio.saveHostConfig({...h.config,chatPlatforms:[],commentary:false,modelProvider:'compatible'});await window.studio.startHost();const next=structuredClone(h.config.layouts);next.twitch.chat.x=1400;await window.studio.saveHostLayouts(next);await window.studio.stopHost();});assert(!(await page.evaluate(()=>window.studio.hostSnapshot())).running);assert.equal((await page.evaluate(()=>window.studio.snapshot())).mode,'manual');assert.deepEqual(errors,[]);console.log(JSON.stringify({ui:true,languages:5,dragPersisted:true,platformLayoutsIsolated:true,layoutEditableWhileHosting:true,localSpeech:speech.testVoice,installedVoices:speech.voices,manualUnaffected:true}));
}finally{if(app){await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});}}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
