// Actual Steam window + three OBS encoders + local model/TTS/avatars.
// Chat is a labelled fixture and replies stay local. This does NOT certify platform chat or public ingestion.
const {_electron:electron}=require('playwright'),{spawn,execFileSync}=require('node:child_process'),fs=require('node:fs/promises'),path=require('node:path');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const hours=Number(process.argv.find(a=>a.startsWith('--hours='))?.split('=')[1]??0),seconds=hours?hours*3600:Number(process.argv.find(a=>a.startsWith('--seconds='))?.split('=')[1]??120);
if(!(seconds>=45&&seconds<=72*3600))throw new Error('Choose 45 seconds to 72 hours');
const compute=process.argv.includes('--gpu')?'auto':'cpu';
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results','host-soak-'+Date.now()),directory=path.join(process.env.LOCALAPPDATA,'JEV Studio HostSoak');await fs.mkdir(out,{recursive:true});const env={...process.env,JEV_TEST_DATA_DIR:directory};delete env.ELECTRON_RUN_AS_NODE;delete env.JEV_DEV_URL;let app;const receivers=[];
try{
 for(let i=0;i<3;i++){const child=spawn('ffmpeg',['-hide_banner','-loglevel','error','-listen','1','-i',`rtmp://127.0.0.1:${19451+i}/live/fixture`,'-c','copy','-f','null','-'],{windowsHide:true,stdio:'ignore'});child.on('error',()=>{});receivers.push(child);}await pause(700);
 app=await electron.launch({args:[root],env,timeout:60000});const page=await app.firstWindow();await page.waitForSelector('.studio-grid');
 await app.evaluate(async({safeStorage},{root,directory,compute})=>{
  const require=process.getBuiltinModule('module').createRequire(root+'/package.json'),join=require('node:path').join;const {Store}=require(join(root,'dist-main/electron/storage.js')),{Obs,obsPorts}=require(join(root,'dist-main/electron/obs.js')),{Hosting}=require(join(root,'dist-main/electron/hosting.js')),{OverlayServer}=require(join(root,'dist-main/electron/overlay-server.js')),{Steam}=require(join(root,'dist-main/electron/steam.js')),{Game}=require(join(root,'dist-main/electron/game.js'));
  Object.assign(obsPorts,{youtube:44751,twitch:44752,x:44753});const store=new Store(directory,safeStorage);await store.init();await store.saveSettings({...await store.settings(),enabledPlatforms:['youtube','twitch','x'],steamAppId:'5272970',addedSteamGames:['5272970']});
  const obs=new Obs(store,()=>{}),game=new Game(store,()=>{},new Steam(async()=>{}),join(root,'dist-native/SteamObserver.exe'));
  const host=new Hosting(store,{credentials:async()=>{throw new Error('No credentials in local soak');}},()=>JSON.stringify({game:game.selected?.name,connected:game.connected,phase:game.connected?game.state?.phase:'unknown',visibleText:game.connected?game.observation?.lines?.map(l=>l.text).join(' ').slice(0,1500):''}),()=>undefined);
  globalThis.hostSoak={obs,game,host,startedAt:0,replies:[],server:null};await game.init();await obs.setup();let target;for(let attempt=0;attempt<20;attempt++){target=(await obs.windows()).find(w=>/LyraGame-Win64-Shipping\.exe/i.test(w.value));if(target)break;await new Promise(r=>setTimeout(r,500));}if(!target)throw new Error('Installed Steam Playtest window must be running; editor capture is never substituted');await obs.capture(target.value);
  await host.init();await host.save({...host.config,compute,model:'qwen3.5:4b',modelProvider:'ollama',apiBase:'http://127.0.0.1:11434',chatPlatforms:[],commentary:true,textReplies:true,intervalSec:30,maxPerHour:120,voice:host.voices.find(v=>v.language==='zh-CN')?.name??'',language:'zh-CN'});
  host.chat.send=async(message,text)=>{if(!message.id.startsWith('local-fixture-'))throw new Error('Unexpected external reply');globalThis.hostSoak.replies.push({platform:message.platform,id:message.id,length:text.length});if(globalThis.hostSoak.replies.length>200)globalThis.hostSoak.replies.shift();};
  const server=new OverlayServer(host,join(root,'dist'));globalThis.hostSoak.server=server;await server.start();for(const [i,p] of ['youtube','twitch','x'].entries()){if(obs.states[p].active)throw new Error('Refusing active output');await obs.overlay(p,server.url(p),host.config.layouts[p]);await obs.service(p,`rtmp://127.0.0.1:${19451+i}/live`,'fixture');await obs.start(p);}await host.start();globalThis.hostSoak.startedAt=Date.now();
 },{root,directory,compute});
 const started=Date.now(),samples=[];let firstSample,sampleCount=0,fixture=0,lastFixture=0,lastCapture=0;await fs.writeFile(path.join(out,'build.json'),JSON.stringify({commit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),version:require(root+'/package.json').version,started:new Date(started).toISOString(),scope:'local encoders, synthetic chat, real Steam capture'},null,2));console.log(JSON.stringify({started:new Date(started).toISOString(),seconds,compute,scope:'local-three-encoders-real-Steam-synthetic-chat'}));
 while(Date.now()-started<seconds*1000){
  if(receivers.some(p=>p.exitCode!==null))throw new Error('Local RTMP receiver exited');
  const inject=Date.now()-lastFixture>45000;if(inject){lastFixture=Date.now();fixture++;}
  const sample=await app.evaluate(async(_,args)=>{const {obs,host,game,replies}=globalThis.hostSoak;if(args.inject){const p=args.fixture%2?'twitch':'youtube';host.chat.add({id:'local-fixture-'+args.fixture,platform:p,authorId:'local-fixture',author:'LOCAL TEST',text:['你是真人还是 AI？','现在是什么游戏？','刚才是否赢了？看不出来请直接说明。'][args.fixture%3],at:Date.now(),self:false});}await obs.poll();const gpuStats={};for(const p of ['youtube','twitch','x'])gpuStats[p]=await obs.clients[p].call('GetStats');return {at:Date.now(),outputs:obs.states,obs:gpuStats,host:{running:host.running,error:host.error,stats:host.stats,overlay:host.overlay},game:{connected:game.connected,mode:game.gate.mode,name:game.selected?.name,phase:game.state?.phase},replies:replies.length,memory:process.memoryUsage()};},{inject,fixture});
  try{sample.gpu=execFileSync('nvidia-smi',['--query-gpu=memory.used,utilization.gpu,temperature.gpu','--format=csv,noheader,nounits'],{encoding:'utf8',windowsHide:true}).trim();}catch{}firstSample??=sample;sampleCount++;samples.push(sample);if(samples.length>120)samples.shift();await fs.appendFile(path.join(out,'samples.ndjson'),JSON.stringify(sample)+'\n');
  await fs.writeFile(path.join(out,'latest.json'),JSON.stringify(sample,null,2));
  if(Object.values(sample.outputs).some(s=>!s.active||s.reconnecting))throw new Error('Output stopped or reconnecting');
  if(sample.game.mode!=='manual')throw new Error('Soak changed gameplay mode');
  if(!sample.game.connected)throw new Error('Steam game observation disconnected; outgoing frames alone do not certify game capture');
  if(Date.now()-lastCapture>60*60*1000){lastCapture=Date.now();for(const p of ['youtube','twitch','x']){const image=await app.evaluate(async(_,p)=>globalThis.hostSoak.obs.preview(p),p);await fs.writeFile(path.join(out,`${p}-${Math.floor((Date.now()-started)/1000)}.jpg`),Buffer.from(image.split(',')[1],'base64'));}}
  await fs.writeFile(path.join(out,'progress.json'),JSON.stringify({requestedSeconds:seconds,elapsedSeconds:(Date.now()-started)/1000,completed:false,sampleCount,samples},null,2));
  console.log(JSON.stringify({elapsedSec:Math.round((Date.now()-started)/1000),generated:sample.host.stats.generated,failures:sample.host.stats.failures,audio:Object.fromEntries(Object.entries(sample.host.overlay).map(([p,v])=>[p,v.audioStarted])),gpu:sample.gpu}));await pause(Math.min(30000,seconds*1000-(Date.now()-started)));
 }
 const last=samples.at(-1),first=firstSample;const smoothness=Object.fromEntries(['youtube','twitch','x'].map(p=>{const end=last.obs[p],start=first.obs[p];return [p,{encodeSkipped:end.outputSkippedFrames-start.outputSkippedFrames,encodeTotal:end.outputTotalFrames-start.outputTotalFrames,renderSkipped:end.renderSkippedFrames-start.renderSkippedFrames,renderTotal:end.renderTotalFrames-start.renderTotalFrames}];}));await fs.writeFile(path.join(out,'smoothness.json'),JSON.stringify(smoothness,null,2));if(Object.values(smoothness).some(s=>s.encodeSkipped/Math.max(1,s.encodeTotal)>.01||s.renderSkipped/Math.max(1,s.renderTotal)>.01))throw new Error('Rendering or encoding skipped more than 1% of frames');if(last.host.stats.generated<1||last.host.stats.spoken<1||last.host.stats.failures>0||Object.values(last.host.overlay).some(v=>v.audioStarted<1||v.audioErrors>0))throw new Error('Hosting, local speech or OBS browser audio did not pass');await fs.writeFile(path.join(out,'report.json'),JSON.stringify({completed:true,scope:'Local pipeline; synthetic chat; real Steam capture; no platform ingestion',requestedSeconds:seconds,elapsedSeconds:(Date.now()-started)/1000,compute,smoothness,sampleCount,samples},null,2));console.log('PASS '+out);
}catch(error){await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({completed:false,passed:false,at:new Date().toISOString(),reason:error instanceof Error?error.message.slice(0,250):'test_failed'},null,2));throw error;}finally{if(app){await app.evaluate(async()=>{const s=globalThis.hostSoak;if(!s)return;s.host.stop();s.server?.close();await s.game.close();for(const p of ['youtube','twitch','x']){await s.obs.stop(p).catch(()=>{});await s.obs.clearKey(p).catch(()=>{});await s.obs.clients[p]?.disconnect();}}).catch(()=>{});await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});}for(const p of receivers)if(p.exitCode===null)p.kill();}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
