<script setup lang="ts">
import HostPanel from './HostPanel.vue';
import { ref, onMounted, onUnmounted, computed, nextTick } from 'vue';
import { providers, providerNames, type Snapshot, type Settings, type Provider, type OAuthProvider } from '../shared/types';
import { t as translate, translateMessage, normalizeLocale, type Locale, type MessageKey } from '../shared/i18n';
const api=window.studio;
const showLibrary=ref(false),librarySearch=ref('');
const s=ref<Snapshot>(),edit=ref<Settings>(),page=ref<'studio'|'settings'|'host'>('studio');
const locale=ref<Locale>('zh-CN');
const languages=[{value:'zh-CN',name:'简体中文'},{value:'zh-TW',name:'繁體中文'},{value:'ja',name:'日本語'},{value:'ko',name:'한국어'},{value:'en',name:'English'}];
const addedGames=computed(()=>s.value?.steamGames.filter(g=>s.value?.settings.addedSteamGames.includes(g.appId))??[]);
const libraryGames=computed(()=>s.value?.steamGames.filter(g=>g.name.toLowerCase().includes(librarySearch.value.toLowerCase()))??[]);
const t=(key:MessageKey,params:Record<string,string|number>={})=>translate(locale.value,key,params);
const tr=(value:string|undefined)=>translateMessage(locale.value,value??'');
const phase=(value:string|undefined)=>t(('phase.'+(value||'loading')) as MessageKey);
const output=ref<Provider>('youtube'),preview=ref(''),notice=ref(''),key=ref(''),pending=ref('');
const xName=ref('JEV Studio'),xServer=ref(''),xKey=ref('');
const icons:Record<Provider,string>={youtube:'▶',twitch:'▣',x:'𝕏'};
const configured=(p:Provider)=>p==='x'?!!s.value?.xSource.configured:!!s.value?.accounts[p];
const channelName=(p:Provider)=>p==='x'?(s.value?.xSource.name||t('x.notConfigured')):(s.value?.accounts[p]?.name||t('account.none'));
const windows=ref<{label:string;value:string}[]>([]),selected=ref('');let timer:ReturnType<typeof setInterval>,previewAt=0,polling=false,lastGameWindow:string|undefined;
const ready=computed(()=>!!s.value?.settings.enabledPlatforms.length&&!!s.value.selectedGame&&!!s.value.settings.gameWindow&&s.value.settings.enabledPlatforms.every(p=>configured(p)&&s.value!.outputs[p].ready));
const youtubeLiveBlocked=computed(()=>{try{return notice.value.startsWith('@jev:')&&JSON.parse(notice.value.slice(5)).key==='error.youtubeLiveUnavailable';}catch{return false;}});
const captureReady=computed(()=>s.value?.settings.enabledPlatforms.some(p=>s.value?.outputs[p].ready));
const active=computed(()=>!!s.value&&s.value.broadcast.state!=='idle');
const streamState=computed(()=>t(('stream.'+(s.value?.broadcast.state||'idle')) as MessageKey));
async function refresh(){
 if(polling)return;polling=true;
 try{s.value=await api.snapshot();if(!edit.value)edit.value={...s.value.settings};locale.value=s.value.settings.locale;document.documentElement.lang=locale.value;if(lastGameWindow!==s.value.settings.gameWindow){selected.value=s.value.settings.gameWindow;lastGameWindow=s.value.settings.gameWindow;}
 if(page.value==='studio'&&s.value.outputs[output.value].connected&&Date.now()-previewAt>3000){previewAt=Date.now();preview.value=await api.preview(output.value).catch(()=>'');}}
 catch(e){notice.value=e instanceof Error?e.message:String(e);}finally{polling=false;}
}
async function run(name:string,fn:()=>Promise<unknown>){pending.value=name;notice.value='';try{await fn();await refresh();}catch(e){notice.value=e instanceof Error?e.message:String(e);}finally{pending.value='';}}
async function changeLocale(){const value=normalizeLocale(locale.value);await run('language',async()=>{await api.setLocale(value);if(edit.value)edit.value.locale=value;document.documentElement.lang=value;});}
function connect(p:OAuthProvider){void run(`login-${p}`,()=>api.connectAccount(p));}
async function openXSetup(){page.value='settings';await nextTick();document.getElementById('x-settings')?.scrollIntoView({behavior:'smooth',block:'center'});}
async function saveX(){const value={name:xName.value,server:xServer.value,key:xKey.value};xKey.value='';await run('xSave',async()=>{await api.saveXSource(value);xServer.value='';notice.value='@jev:'+JSON.stringify({key:'event.xSaved'});});}
async function save(){if(edit.value)await run('save',async()=>{await api.saveSettings({...edit.value!});notice.value='@jev:'+JSON.stringify({key:'settings.saved'});});}
async function importGoogle(){await run('import',async()=>{if(await api.importGoogleClient()){s.value=await api.snapshot();edit.value={...s.value.settings};}});}
async function refreshWindows(){await run('windows',async()=>{windows.value=await api.windows();const name=s.value?.selectedGame?.name??'';const game=windows.value.find(w=>(name&&w.label.toLowerCase().includes(name.toLowerCase()))||(s.value?.settings.steamAppId==='5272970'&&/LyraGame-Win64-Shipping\.exe/i.test(w.value)));if(game&&!selected.value)selected.value=game.value;});}
async function openLibrary(){showLibrary.value=true;await run('scan',()=>api.scanSteam());}
async function selectGame(id:string){await run('select',async()=>{await api.selectSteamGame(id);selected.value='';preview.value='';edit.value=undefined;});}
async function togglePlatform(p:Provider,event:Event){await run('platform',async()=>{const current=(await api.snapshot()).settings;const selected=current.enabledPlatforms.includes(p)?current.enabledPlatforms.filter(item=>item!==p):[...current.enabledPlatforms,p];await api.selectPlatforms(selected);edit.value=undefined;if(selected.length&&!selected.includes(output.value)){output.value=selected[0];preview.value='';previewAt=0;}});(event.target as HTMLInputElement).checked=s.value!.settings.enabledPlatforms.includes(p);}
async function addGame(id:string){await run('add',async()=>{await api.addSteamGame(id);if(!s.value?.settings.steamAppId){await api.selectSteamGame(id);selected.value='';preview.value='';edit.value=undefined;}});}
function open(url:string){void run('open',()=>api.openExternal(url));}
onMounted(async()=>{if(!api){notice.value=t('app.desktopOnly');return;}await refresh();timer=setInterval(refresh,1000);});
onUnmounted(()=>clearInterval(timer));
</script>

<template>
 <div class="shell">
  <aside class="sidebar">
   <div class="brand"><span class="brand-mark">J</span><div>JEV <b>Studio</b><small>{{t('app.tagline')}}</small></div></div>
   <div class="workspace"><span class="workspace-icon">✦</span><div>{{t('app.workspace')}}<small>{{t('app.localWorkspace')}}</small></div><span class="chevron">⌄</span></div>
   <div class="nav-label">{{t('nav.workspace')}}</div>
   <button class="nav-item" :class="{chosen:page==='studio'}" @click="page='studio'"><span>▣</span>{{t('nav.studio')}}</button>
   <button class="nav-item" :class="{chosen:page==='host'}" @click="page='host'"><span>✧</span>{{t('host.title')}}</button>
   <button class="nav-item" :class="{chosen:page==='settings'}" @click="page='settings'"><span>⚙</span>{{t('nav.settings')}}</button>
   <div class="sidebar-bottom"><button class="author-card" @click="open('https://x.com/jackzhj')"><span class="author-x">𝕏</span><span><b>{{t('author.label')}}</b><small>{{t('author.invite')}}</small></span></button><span class="dot"></span>{{t('app.phase')}}<small>{{t('app.features')}}</small><div class="version">JEV STUDIO <span>v0.1.0</span></div></div>
  </aside>
  <main>
   <header><div class="breadcrumb">{{t('nav.workspace')}} <span>/</span> {{t(page==='host'?'host.title':page==='studio'?'nav.studio':'nav.settings')}}</div><div class="header-actions"><select id="language" class="language-select" :aria-label="t('app.language')" v-model="locale" @change="changeLocale"><option v-for="item in languages" :value="item.value" :key="item.value">{{item.name}}</option></select><div class="local-badge"><span class="dot"></span>{{t('app.localSecure')}}</div></div></header>
   <div v-if="notice" class="notice" role="alert"><span>{{tr(notice)}}</span><button v-if="youtubeLiveBlocked" class="notice-action" @click="open('https://studio.youtube.com')">{{t('live.youtubeStudio')}}</button><button :aria-label="t('common.closeNotice')" @click="notice=''">×</button></div>
   <template v-if="s">
    <section class="page-heading"><div><p class="eyebrow">{{t(page==='host'?'host.localModel':page==='studio'?'eyebrow.studio':'eyebrow.settings')}}</p><h1>{{t(page==='host'?'host.title':page==='studio'?'heading.studio':'heading.settings')}}</h1><p class="subtitle">{{t(page==='host'?'host.subtitle':page==='studio'?'heading.studioSubtitle':'heading.settingsSubtitle')}}</p></div><div v-if="page==='studio'" class="session-status"><span class="dot" :class="{on:active}"></span>{{streamState}}</div></section>
    <template v-if="page==='studio'">
     <div class="studio-grid"><div class="primary-column">
      <section class="card preview-card">
       <div class="card-toolbar"><div class="segmented"><button v-for="p in providers" :key="p" :class="{selected:output===p}" @click="output=p;preview='';previewAt=0"><span :class="p">{{icons[p]}}</span> {{providerNames[p]}}</button></div><span class="meta">1920 × 1080 <span>{{60}} FPS</span></span></div>
       <div class="preview"><img v-if="preview" :src="preview" :alt="t('preview.alt')"><div v-else class="preview-empty"><div class="cube-icon">◇</div><h2>{{t('preview.title')}}</h2><p>{{t('preview.description')}}</p><button class="light-button" :disabled="!!s.busy" @click="run('obs',()=>api.setupOBS())">{{s.busy?tr(s.busy):t('obs.prepare')}}</button></div><div class="preview-label">{{t(preview?'preview.live':'preview.wait')}} <span>{{output.toUpperCase()}}</span></div></div>
       <div class="capture-row"><select :aria-label="t('capture.select')" v-model="selected"><option value="">{{t('capture.select')}}</option><option v-if="selected&&!windows.some(w=>w.value===selected)" :value="selected">{{selected}}</option><option v-for="w in windows" :key="w.value" :value="w.value">{{w.label}}</option></select><button :disabled="!captureReady" @click="refreshWindows">{{t('common.refresh')}}</button><button :disabled="!selected||!!s.busy" @click="run('capture',()=>api.setCapture(selected))">{{t('common.apply')}}</button></div>
      </section>
      <section class="card game-card">
       <div class="section-title"><div><span class="small-icon">&#x2318;</span><h2>{{t('steam.heading')}}</h2><span class="pill" :class="{green:s.gameConnected}">{{t(s.gameConnected?'game.connected':'game.disconnected')}}</span></div><button class="text-button" @click="openLibrary">+ {{t('steam.add')}}</button></div>
       <div class="steam-selection"><select :aria-label="t('steam.choose')" :value="s.settings.steamAppId" :disabled="active||s.mode==='auto'||!!s.busy" @change="selectGame(($event.target as HTMLSelectElement).value)"><option value="" disabled>{{t('steam.empty')}}</option><option v-for="g in addedGames" :key="g.appId" :value="g.appId">{{g.name}}</option></select><button :disabled="!s.selectedGame||!!s.busy" @click="run('game',()=>api.launchGame())">{{t('steam.launch')}}</button></div>
       <div class="game-summary"><div class="game-art">{{s.selectedGame?.appId==='5272970'?'ETC':'S'}}<span>STEAM</span></div><div><h3>{{s.selectedGame?.name||t('steam.choose')}}</h3><p>{{t(s.selectedGame?.autoSupport==='experimental'?'steam.experimental':'steam.manualOnly')}}</p></div><div class="mode-switch"><button :class="{selected:s.mode==='manual'}" @click="run('manual',()=>api.setMode('manual'))">{{t('mode.manual')}}</button><button :class="{selected:s.mode==='auto'}" :disabled="!s.gameConnected||!s.autoplay.connected||s.selectedGame?.autoSupport!=='experimental'" @click="run('auto',()=>api.setMode('auto'))">&#x2726; {{t('mode.auto')}}</button></div></div>
       <div class="game-detail"><span>{{s.gameConnected?phase(s.game?.phase):t('steam.screenControl')}}</span><span>{{t('game.takeover')}} <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>M</kbd></span></div><div class="decision"><span class="dot" :class="{on:s.mode==='auto'}"></span>{{tr(s.gameError||s.decision)}}</div>
       <div v-if="s.selectedGame?.appId==='5272970'" class="autoplay-metrics" data-testid="autoplay-metrics"><b>{{t('etc.metrics')}}</b><span>{{t('etc.latency')}} {{s.autoplay.decisions?Math.round(s.autoplay.p95LatencyMs):'?'}} ms</span><span>{{t('etc.results')}} {{s.autoplay.wins}} / {{s.autoplay.matches}}</span><span>{{t('etc.ammo')}} {{s.autoplay.magazine>=0?s.autoplay.magazine:'?'}} / {{s.autoplay.reserve>=0?s.autoplay.reserve:'?'}}</span><small>{{t('etc.scope')}}</small></div>
      </section>
     </div><div class="secondary-column">
      <section class="card channels-card"><div class="section-title"><h2>{{t('channels.title')}}</h2><span class="meta">{{t('channels.count',{count:s.settings.enabledPlatforms.length})}}</span></div>
       <article v-for="p in providers" :key="p" class="channel">
        <div class="channel-heading"><div :class="['platform-icon',p]">{{icons[p]}}</div><div><h3>{{providerNames[p]}}</h3><p>{{channelName(p)}}</p></div><label class="platform-toggle"><input type="checkbox" :checked="s.settings.enabledPlatforms.includes(p)" :aria-label="t('channels.include',{provider:providerNames[p]})" :disabled="active||!!pending||!!s.busy" @change="togglePlatform(p,$event)">{{t('channels.enabled')}}</label></div>
        <template v-if="p==='x'"><small class="x-source-status">{{t(s.xSource.configured?'x.savedStatus':'x.connectionHint')}}</small><button class="connect-button" :disabled="active||!!pending||!!s.busy" @click="openXSetup">{{t(s.xSource.configured?'x.manage':'x.configure')}}</button></template>
        <template v-else><div v-if="s.auth[p]" class="auth-state">{{tr(s.auth[p])}}<button @click="api.cancelLogin(p)">{{t('account.cancel')}}</button></div><button v-else-if="!s.accounts[p]" class="connect-button" @click="connect(p)">{{t('account.login',{provider:p==='youtube'?'Google':'Twitch'})}}</button></template>
        <div v-if="configured(p)" class="channel-stats"><span><i class="dot" :class="{on:s.outputs[p].active}"></i>{{t(s.outputs[p].active?'obs.streaming':s.outputs[p].ready?'obs.ready':'obs.waiting')}}</span><button v-if="p!=='x'" class="text-button" :disabled="active" @click="run('disconnect',()=>api.disconnectAccount(p))">{{t('account.logout')}}</button><button v-else class="text-button" @click="open('https://x.com/i/live-studio')">{{t('x.openStudio')}}</button></div>
        <div class="output-metrics"><span>{{t('metrics.sent')}} <b>{{(s.outputs[p].bytes/1048576).toFixed(1)}} MB</b></span><span>{{t('metrics.dropped')}} <b>{{s.outputs[p].skipped}}</b></span></div>
       </article><button class="text-button setup-link" :disabled="!!s.busy" @click="run('obs',()=>api.setupOBS())">{{s.busy?tr(s.busy):t('obs.connect')}} ↗</button></section>
      <section class="card live-card"><h2>{{t('live.title')}}</h2><p>{{t('live.description')}}</p><div v-if="s.settings.enabledPlatforms.includes('youtube')" class="visibility"><span>YouTube</span><b>{{t(('privacy.'+s.settings.youtubePrivacy) as MessageKey)}}</b></div><div v-if="s.settings.enabledPlatforms.includes('twitch')" class="visibility"><span>Twitch</span><b>{{t('privacy.publicLive')}}</b></div><div v-if="s.settings.enabledPlatforms.includes('x')" class="x-live-note"><b>𝕏 {{t('x.visibility')}}</b><p>{{t('x.liveHint')}}</p><button class="text-button" @click="open('https://x.com/i/live-studio')">{{t('x.openStudio')}}</button></div><button v-if="!active" class="primary-button" :disabled="!ready||!!s.busy" @click="run('start',()=>api.startStream())"><span>◉</span>{{t('live.start')}}</button><button v-else class="stop-button" :disabled="!!s.busy" @click="run('stop',()=>api.stopStream())">■ {{t('live.stop')}}</button><small>{{t(!s.settings.enabledPlatforms.length?'channels.minimum':!ready?'live.notReady':'live.disclosure')}}</small><button v-if="s.broadcast.youtubeUrl" class="text-button" @click="open(s.broadcast.youtubeUrl)">{{t('live.view',{provider:'YouTube'})}}</button><button v-if="s.broadcast.twitchUrl" class="text-button" @click="open(s.broadcast.twitchUrl)">{{t('live.view',{provider:'Twitch'})}}</button></section>
     </div></div>
     <section class="card activity-card"><div class="section-title"><h2>{{t('activity.title')}}</h2><span class="meta">{{t('activity.note')}}</span></div><div v-for="(item,i) in s.logs.slice(0,5)" :key="i" class="log-line"><time>{{new Date(item.at).toLocaleTimeString(locale)}}</time><span>{{tr(item.message)}}</span></div></section><p class="phase-note">{{t('app.scope')}}</p>
    </template>
    <HostPanel v-else-if="page==='host'" :locale="locale"/>
    <div v-else-if="edit" class="settings-grid">
     <section class="card settings-card"><p class="eyebrow">{{t('eyebrow.accounts')}}</p><h2>{{t('settings.accounts')}}</h2><p>{{t('settings.accountHint')}}</p><label>Google Desktop Client ID<input v-model="edit.googleClientId" placeholder="…apps.googleusercontent.com" autocomplete="off"></label><div class="inline-buttons"><button @click="importGoogle">{{t('settings.googleImport')}}</button><button class="text-button" @click="open('https://console.cloud.google.com/apis/credentials')">{{t('settings.googleConsole')}}</button></div><label>Twitch Public Client ID<input v-model="edit.twitchClientId" :placeholder="t('settings.clientPlaceholder')" autocomplete="off"></label><button class="text-button" @click="open('https://dev.twitch.tv/console/apps')">{{t('settings.twitchRegister')}}</button><div class="info-box">{{t('settings.oauthHint')}}</div></section>
     <section id="x-settings" class="card settings-card x-settings"><p class="eyebrow">𝕏 LIVE STUDIO</p><h2>{{t('x.configure')}}</h2><p>{{t('x.setupHint')}}</p><button class="text-button" @click="open('https://x.com/i/live-studio')">{{t('x.openStudio')}}</button><div v-if="s.xSource.configured" class="info-box">{{s.xSource.name}} · {{t('x.savedStatus')}}</div><label>{{t('x.sourceName')}}<input v-model="xName" maxlength="80" autocomplete="off"></label><label>{{t('x.server')}}<input v-model="xServer" type="text" autocomplete="off" spellcheck="false" placeholder="rtmps://…"></label><label>{{t('x.key')}}<input v-model="xKey" type="password" autocomplete="new-password" spellcheck="false" :placeholder="t('x.keyPlaceholder')"></label><div class="inline-buttons"><button class="primary-button" :disabled="active||!!pending||!!s.busy||!xName.trim()||!xServer.trim()||!xKey" @click="saveX">{{t('x.save')}}</button><button v-if="s.xSource.configured" class="text-button" :disabled="active||!!pending||!!s.busy" @click="run('xRemove',()=>api.removeXSource())">{{t('x.remove')}}</button></div><small>{{t('x.localOnly')}}</small></section>
     <section class="card settings-card"><p class="eyebrow">{{t('eyebrow.game')}}</p><h2>{{t('settings.game')}}</h2><p>{{t('steam.selectNote')}}</p><label>{{t('settings.policy')}}<select v-model="edit.decisionProvider"><option value="rules">{{t('settings.rules')}}</option><option value="jev">{{t('settings.jev')}}</option></select></label><label>JEV API Key <span class="label-detail">{{t(s.hasJevKey?'settings.keySaved':'settings.keyMissing')}}</span><div class="input-button"><input type="password" v-model="key" autocomplete="new-password" :placeholder="t('settings.keyPlaceholder')"><button :disabled="!key" @click="run('key',async()=>{await api.saveJevKey(key);key='';})">{{t('settings.saveKey')}}</button></div></label><label>{{t('settings.interval')}}<input type="number" min="300" max="5000" v-model.number="edit.decisionIntervalMs"></label><label class="checkbox"><input type="checkbox" v-model="edit.autoRestart">{{t('settings.restart')}}</label><div class="info-box">{{t('steam.controlHint')}}</div></section>
     <section class="card settings-card"><p class="eyebrow">{{t('eyebrow.broadcast')}}</p><h2>{{t('settings.broadcast')}}</h2><label>{{t('settings.title')}}<input v-model="edit.title" maxlength="100"></label><div class="form-row"><label>{{t('settings.visibility')}}<select v-model="edit.youtubePrivacy"><option value="private">{{t('settings.privateRecommended')}}</option><option value="unlisted">{{t('privacy.unlisted')}}</option><option value="public">{{t('privacy.public')}}</option></select></label><label>{{t('settings.bitrate')}}<input type="number" v-model.number="edit.bitrate" min="1500" max="8000"></label></div><label>{{t('settings.obs')}}<input v-model="edit.obsDirectory"></label><div class="info-box">{{t('settings.obsHint')}}</div></section>
     <section class="card settings-card next-card"><div class="orb">✦</div><h2>{{t('settings.once')}}</h2><p>{{t('settings.independent')}}</p><button class="primary-button" :disabled="!!pending||!!s.busy" @click="save">{{t('settings.save')}}</button><button class="text-button" @click="page='studio'">{{t('settings.back')}}</button><small>{{t('settings.alpha')}}</small></section>
    </div>
   </template><div v-else class="loading">{{t('app.loading')}}</div>
  </main>
  <div v-if="showLibrary" class="modal-backdrop" @click.self="showLibrary=false"><section class="library-dialog" role="dialog" aria-modal="true" :aria-label="t('steam.installed')"><div class="section-title"><h2>{{t('steam.installed')}}</h2><button :aria-label="t('common.closeNotice')" @click="showLibrary=false">&#xd7;</button></div><p>{{t('steam.selectNote')}}</p><div class="library-filter"><input v-model="librarySearch" :placeholder="t('steam.choose')" :aria-label="t('steam.choose')"><button :disabled="!!s?.busy" @click="run('scan',()=>api.scanSteam())">{{t('steam.scan')}}</button></div><p v-if="!libraryGames.length">{{t('steam.notDetected')}}</p><article v-for="g in libraryGames" :key="g.appId" class="library-game"><div><b>{{g.name}}</b><small>Steam {{g.appId}} ? {{t(g.autoSupport==='experimental'?'steam.experimental':'steam.manualOnly')}}</small></div><button v-if="!s?.settings.addedSteamGames.includes(g.appId)" @click="addGame(g.appId)">{{t('steam.addButton')}}</button><template v-else><span>{{t('steam.added')}}</span><button :disabled="active||s?.mode==='auto'" @click="run('remove',()=>api.removeSteamGame(g.appId))">{{t('steam.remove')}}</button></template></article></section></div>
 </div>
</template>
