<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';import Avatar from './Avatar.vue';import type {OverlayState,LayerRect} from '../shared/hosting';
const state=ref<OverlayState>(),level=ref(0),prefix='/'+location.pathname.split('/')[1],provider=location.pathname.split('/')[3];let timer:ReturnType<typeof setInterval>,loading=false,last='',lastSeen=Date.now(),audio:AudioContext|undefined,source:AudioBufferSourceNode|undefined,analyser:AnalyserNode|undefined,frame=0;
const stopAudio=()=>{try{source?.stop();source?.disconnect();}catch{}source=undefined;analyser?.disconnect();analyser=undefined;level.value=0;};
const style=(r:LayerRect)=>({left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px',display:r.visible?'':'none'});
async function sync(){if(loading)return;loading=true;try{const r=await fetch(`${prefix}/state/${provider}`,{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw new Error('offline');state.value=await r.json();lastSeen=Date.now();const speech=state.value?.utterance;if(!speech){stopAudio();return;}if(speech.id===last)return;last=speech.id;stopAudio();if(!speech.audio)return;
 audio??=new AudioContext();await audio.resume();if(audio.state!=='running')throw new Error('audio suspended');const data=await fetch(`${prefix}/audio/${speech.audio}`,{signal:AbortSignal.timeout(3000)});const buffer=await audio.decodeAudioData(await data.arrayBuffer());if(state.value?.utterance?.id!==speech.id||Date.now()>speech.expires)return;source=audio.createBufferSource();source.buffer=buffer;analyser=audio.createAnalyser();analyser.fftSize=256;source.connect(analyser);analyser.connect(audio.destination);source.start();void fetch(`${prefix}/ack/${provider}`,{method:'POST'});
 }catch{void fetch(`${prefix}/ack/${provider}?kind=error`,{method:'POST'}).catch(()=>{});}finally{loading=false;}}
function animate(){if(Date.now()-lastSeen>5000){state.value=undefined;stopAudio();}if(state.value?.utterance&&Date.now()>state.value.utterance.expires){state.value.utterance=null;stopAudio();}if(analyser){const values=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(values);level.value=Math.sqrt(values.reduce((sum,v)=>sum+(v-128)**2,0)/values.length)/128;}frame=requestAnimationFrame(animate);}
onMounted(()=>{void sync();timer=setInterval(sync,300);animate();});onBeforeUnmount(()=>{clearInterval(timer);cancelAnimationFrame(frame);void audio?.close();});
</script>
<template><div class="stage" v-if="state"><div class="layer" :style="style(state.layout.avatar)"><Avatar :avatar="state.avatar" :url="state.avatar.asset?`${prefix}/avatar/${state.avatar.asset}`:''" :level="level"/></div><div v-if="state.provider!=='x'&&state.messages.length" class="layer chat" :style="style(state.layout.chat)"><div class="chat-title">{{state.provider==='youtube'?'YouTube':state.provider==='twitch'?'Twitch':'X'}} <span>{{({'zh-CN':'直播聊天','zh-TW':'直播聊天',ja:'ライブチャット',ko:'실시간 채팅',en:'LIVE CHAT'})[state.language]}}</span></div><article v-for="m in state.messages.slice(-7)" :key="m.id"><b>{{m.author}}</b><p>{{m.text}}</p></article></div><div v-if="state.utterance" class="layer captions" :style="style(state.layout.captions)"><span>{{state.avatar.name}}</span><p>{{state.utterance.text}}</p></div></div></template>
<style>html,body,#app{margin:0;width:1920px;height:1080px;background:transparent;overflow:hidden;font-family:Inter,'Segoe UI','Microsoft YaHei',sans-serif}.stage{position:relative;width:1920px;height:1080px}.layer{position:absolute;box-sizing:border-box}.chat{display:flex;flex-direction:column;justify-content:flex-end;gap:10px;overflow:hidden;color:#fff}.chat-title{padding:14px 20px;border-radius:14px;background:#11182bd9;font-size:21px;font-weight:700}.chat-title span{float:right;font-size:12px;letter-spacing:2px;opacity:.6}article{padding:16px 20px;border-radius:14px;background:#11182bdb;border:1px solid #ffffff18;overflow-wrap:anywhere}article b{font-size:18px;color:#c7baff}article p{margin:6px 0 0;font-size:22px;line-height:1.35}.captions{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;text-align:center;color:white}.captions span{font-size:16px;border-radius:8px;background:#8c78db;padding:3px 14px}.captions p{margin:0;border-radius:12px;background:#101522dc;padding:12px 24px;font-size:25px;line-height:1.35;max-width:100%;overflow:hidden;max-height:90px}</style>
