<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';import Avatar from './Avatar.vue';import type {OverlayState,LayerRect,OverlayEvent} from '../shared/hosting';import {OverlayAudio} from './overlay-audio';
const state=ref<OverlayState>(),level=ref(0),prefix='/'+location.pathname.split('/')[1],provider=location.pathname.split('/')[3];let timer:ReturnType<typeof setInterval>,loading=false,lastSeen=Date.now(),frame=0,disconnected=false,stopped=false,lastStateError=0;
const report=(kind:OverlayEvent,code='')=>{void fetch(`${prefix}/ack/${provider}?kind=${kind}&code=${encodeURIComponent(code)}`,{method:'POST',signal:AbortSignal.timeout(3000)}).catch(()=>{});};
const player=new OverlayAudio(prefix,report,()=>state.value?.utterance);
const style=(r:LayerRect)=>({left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px',display:r.visible?'':'none'});
async function sync(){if(loading||stopped)return;loading=true;try{const r=await fetch(`${prefix}/state/${provider}`,{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw new Error('http_'+r.status);const next=await r.json();if(stopped)return;state.value=next;lastSeen=Date.now();disconnected=false;void player.sync(state.value?.utterance);
 }catch(e){if(!stopped&&Date.now()-lastStateError>10000){lastStateError=Date.now();report('stateError',e instanceof Error&&/^http_\d+$/.test(e.message)?e.message:'state_timeout_or_fetch');}}finally{loading=false;}}
function animate(){if(Date.now()-lastSeen>5000&&!disconnected){disconnected=true;state.value=undefined;player.stop(true);}if(state.value?.utterance&&Date.now()>state.value.utterance.expires){state.value.utterance=null;void player.sync(null);}level.value=player.sample();frame=requestAnimationFrame(animate);}
onMounted(()=>{void sync();timer=setInterval(sync,300);animate();});onBeforeUnmount(()=>{stopped=true;clearInterval(timer);cancelAnimationFrame(frame);player.close();});
</script>
<template><div class="stage" v-if="state"><div v-if="state.gameConnected===false" class="game-waiting"><b>{{({'zh-CN':'正在等待游戏画面','zh-TW':'正在等待遊戲畫面',ja:'ゲーム映像を待っています',ko:'게임 화면을 기다리는 중',en:'Waiting for the game'})[state.language]}}</b></div><div class="layer" :style="style(state.layout.avatar)"><Avatar :avatar="state.avatar" :url="state.avatar.asset?`${prefix}/avatar/${state.avatar.asset}`:''" :level="level"/></div><div v-if="(state.provider!=='x'||state.simulation)&&state.messages.length" class="layer chat" :style="style(state.layout.chat)"><div class="chat-title">{{state.simulation?'SIMULATED CHAT':state.provider==='youtube'?'YouTube':state.provider==='twitch'?'Twitch':'X'}} <span>{{({'zh-CN':'直播聊天','zh-TW':'直播聊天',ja:'ライブチャット',ko:'실시간 채팅',en:'LIVE CHAT'})[state.language]}}</span></div><article v-for="m in state.messages.slice(-7)" :key="m.id"><b>{{m.author}}</b><p>{{m.text}}</p></article></div><div v-if="state.utterance" class="layer captions" :style="style(state.layout.captions)"><span>{{state.avatar.name}}</span><p>{{state.utterance.text}}</p></div></div></template>
<style>html,body,#app{margin:0;width:1920px;height:1080px;background:transparent;overflow:hidden;font-family:Inter,'Segoe UI','Microsoft YaHei',sans-serif}.stage{position:relative;width:1920px;height:1080px}.game-waiting{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:#111525f5;color:#e8e4ff;font-size:42px;font-weight:600}.layer{position:absolute;box-sizing:border-box}.chat{display:flex;flex-direction:column;justify-content:flex-end;gap:10px;overflow:hidden;color:#fff}.chat-title{padding:14px 20px;border-radius:14px;background:#11182bd9;font-size:21px;font-weight:700}.chat-title span{float:right;font-size:12px;letter-spacing:2px;opacity:.6}article{padding:16px 20px;border-radius:14px;background:#11182bdb;border:1px solid #ffffff18;overflow-wrap:anywhere}article b{font-size:18px;color:#c7baff}article p{margin:6px 0 0;font-size:22px;line-height:1.35}.captions{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;text-align:center;color:white}.captions span{font-size:16px;border-radius:8px;background:#8c78db;padding:3px 14px}.captions p{margin:0;border-radius:12px;background:#101522dc;padding:12px 24px;font-size:25px;line-height:1.35;max-width:100%;overflow:hidden;max-height:90px}</style>
